name: spiritual_harmony_journal
description: A spiritual journaling app with AI insights.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2  # State management (latest ~6.1.5+1, but ^6.1.2 is compatible)
  sqflite: ^2.4.2
  path: ^1.9.1
  camera: ^0.11.2
  ar_flutter_plugin: ^0.7.3
  google_ml_kit: ^0.20.0
  health: ^13.2.1
  firebase_core: ^3.6.0  # Latest per trends, though tool showed 4.2.0; adjust if needed
  dart_openai: ^5.1.0
  envied: ^1.3.1  # For API key env

dev_dependencies:
  flutter_test:
    sdk: flutter
  envied_generator: ^1.3.1  # For generating env.g.dart
  build_runner: ^2.4.13  # For code generation

flutter:
  uses-material-design: true